name: BuildPlugin
on:
    push:
        branches:
            - main

jobs:
    build:
        uses: FriendsOfShopware/workflows/.github/workflows/github.yml@main
        with:
            extensionName: ${{ github.event.repository.name }}
            shopwareVersion: '6.4.10'
        secrets:
            ghToken: ${{ secrets.GITHUB_TOKEN }}
